name: pizza_delivery
description: The Pizza delivery application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  provider:
  shared_preferences:
  csv: ^4.1.0
  sqflite:
  fluttericon:
  path:
  google_fonts:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/beverages/
    - assets/images/pizzas/
    - assets/images/toppings/
    - assets/images/menus/
    - assets/data/